[2017-04-25 01:17:44] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 01:17:44] application.ERROR: No route found for "GET /api/v1" [] []
[2017-04-25 01:17:44] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-25 01:19:38] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:19:38] application.ERROR: Signature verification failed [] []
[2017-04-25 01:19:38] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\xA1\xBA\x04+\xCAW\x9E+\xAF\xDBy\xA6\x10\x19\x84...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:24:14] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:24:14] application.ERROR: Signature verification failed [] []
[2017-04-25 01:24:14] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'w\xA0\xDB& \xCC\x8B\xADs)\x7F\x06'\r\xBD...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:24:20] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:24:20] application.ERROR: Signature verification failed [] []
[2017-04-25 01:24:20] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\xABz57.\x98\x033![N\xBAPl\x08...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:25:58] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:25:58] application.ERROR: Signature verification failed [] []
[2017-04-25 01:25:58] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\x92\x13Ia:\x9AT\xF2\xB9\f\xA9q\x8E\xBE\x8A...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:29:25] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:29:25] application.ERROR: Signature verification failed [] []
[2017-04-25 01:29:25] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\fe'a\x08\x8B"\xB8[\x91\x10Z\xED\xB9\xB3...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:29:25] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:29:25] application.ERROR: Signature verification failed [] []
[2017-04-25 01:29:25] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\x9B\e\x94\xA3\x89\xB9\xCDam\x1F\xEC\xC4?\x98\xE2...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 01:29:26] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 01:29:26] application.ERROR: Signature verification failed [] []
[2017-04-25 01:29:26] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '\xBA\x81|\xEB\x13\x92\x8E\xAEG*3\xC4a0\xC9...', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:19:29] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:19:29] application.ERROR: Signature verification failed [] []
[2017-04-25 20:19:29] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:19:41] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:19:41] application.ERROR: Signature verification failed [] []
[2017-04-25 20:19:41] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:20:00] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:20:00] application.ERROR: Signature verification failed [] []
[2017-04-25 20:20:00] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:26:17] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:26:17] application.ERROR: Signature verification failed [] []
[2017-04-25 20:26:17] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:26:19] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:26:19] application.ERROR: Signature verification failed [] []
[2017-04-25 20:26:19] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:27:32] application.CRITICAL: Firebase\JWT\SignatureInvalidException: Signature verification failed (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 109 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:109)"} []
[2017-04-25 20:27:32] application.ERROR: Signature verification failed [] []
[2017-04-25 20:27:32] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode(' eyJ0eXAiOiJKV1...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:33:26] application.CRITICAL: Firebase\JWT\BeforeValidException: Cannot handle token prior to 2017-04-25T20:34:26-0300 (uncaught exception) at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php line 115 {"exception":"[object] (Firebase\\JWT\\BeforeValidException(code: 0): Cannot handle token prior to 2017-04-25T20:34:26-0300 at /var/www/html/n2oti/vendor/firebase/php-jwt/src/JWT.php:115)"} []
[2017-04-25 20:33:26] application.ERROR: Cannot handle token prior to 2017-04-25T20:34:26-0300 [] []
[2017-04-25 20:33:26] application.ERROR: #0 /var/www/html/n2oti/src/MyApp/Controller/Provider/Book.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'secret', Array) #1 [internal function]: MyApp\Controller\Provider\Book->MyApp\Controller\Provider\{closure}(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #2 /var/www/html/n2oti/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php(54): call_user_func(Object(Closure), Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application)) #3 [internal function]: Silex\EventListener\MiddlewareListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-04-25 20:36:22] application.ERROR: Uncaught Exception Error: "Call to undefined function MyApp\Controller\strotime()" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 27 {"exception":"[object] (Error(code: 0): Call to undefined function MyApp\\Controller\\strotime() at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:27)"} []
[2017-04-25 20:36:23] application.ERROR: Uncaught Exception Error: "Call to undefined function MyApp\Controller\strotime()" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 27 {"exception":"[object] (Error(code: 0): Call to undefined function MyApp\\Controller\\strotime() at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:27)"} []
[2017-04-25 20:49:39] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "PUT /api/v1/books/": Method Not Allowed (Allow: GET, POST) (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"PUT /api/v1/books/\": Method Not Allowed (Allow: GET, POST) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-04-25 20:49:39] application.ERROR: No route found for "PUT /api/v1/books/": Method Not Allowed (Allow: GET, POST) [] []
[2017-04-25 20:49:39] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-25 21:01:22] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'UPDATE user SET token = ? WHERE id = ?' with params ["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ4ODIsImp0aSI6IkxxOWpvVkVIYXdTZnhoUEphVGo0NlU3dithNnhXZ1wvSmFic1RrXC9LMmp1OD0iLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCIsIm5iZiI6MTQ5MzE2NDg4MiwiZXhwIjoxNDkzMTY1NDg2LCJkYXRhIjp7InVzZXJJZCI6MCwidXNlck5hbWUiOiJmYWJpbyJ9fQ.oI8frP-sVsaIxCFRijgux8QMhmQmuOmNbpkeBKfcJae3GglkQ2S7L9mZWG_2Fpqwz3POciSMuqq1-VDYuotFNw", 0]:  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "user" LINE 1: UPDATE user SET token = $1 WHERE id = $2                ^ (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'UPDATE user SET token = ? WHERE id = ?' with params [\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ4ODIsImp0aSI6IkxxOWpvVkVIYXdTZnhoUEphVGo0NlU3dithNnhXZ1wvSmFic1RrXC9LMmp1OD0iLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCIsIm5iZiI6MTQ5MzE2NDg4MiwiZXhwIjoxNDkzMTY1NDg2LCJkYXRhIjp7InVzZXJJZCI6MCwidXNlck5hbWUiOiJmYWJpbyJ9fQ.oI8frP-sVsaIxCFRijgux8QMhmQmuOmNbpkeBKfcJae3GglkQ2S7L9mZWG_2Fpqwz3POciSMuqq1-VDYuotFNw\", 0]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: UPDATE user SET token = $1 WHERE id = $2\n               ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 42601): SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: UPDATE user SET token = $1 WHERE id = $2\n               ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42601): SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: UPDATE user SET token = $1 WHERE id = $2\n               ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-25 21:01:22] application.ERROR: An exception occurred while executing 'UPDATE user SET token = ? WHERE id = ?' with params ["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ4ODIsImp0aSI6IkxxOWpvVkVIYXdTZnhoUEphVGo0NlU3dithNnhXZ1wvSmFic1RrXC9LMmp1OD0iLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCIsIm5iZiI6MTQ5MzE2NDg4MiwiZXhwIjoxNDkzMTY1NDg2LCJkYXRhIjp7InVzZXJJZCI6MCwidXNlck5hbWUiOiJmYWJpbyJ9fQ.oI8frP-sVsaIxCFRijgux8QMhmQmuOmNbpkeBKfcJae3GglkQ2S7L9mZWG_2Fpqwz3POciSMuqq1-VDYuotFNw", 0]:  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "user" LINE 1: UPDATE user SET token = $1 WHERE id = $2                ^ [] []
[2017-04-25 21:01:22] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE user SET...', Array) #2 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(669): Doctrine\DBAL\Connection->executeUpdate('UPDATE user SET...', Array, Array) #3 /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php(53): Doctrine\DBAL\Connection->update('user', Array, Array) #4 [internal function]: MyApp\Controller\AuthenticateController->authenticate(Object(Silex\Application), Object(Symfony\Component\HttpFoundation\Request)) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2017-04-25 21:01:40] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE public.usuario SET token = ? WHERE id = ?' with params ["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ5MDAsImp0aSI6IjRQS1RPb2FVRVlWZ3ZVYkFoa0JIUmE5WDVzb2g0ajJ1XC9NNnFYN3c3ME44PSIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIiwibmJmIjoxNDkzMTY0OTAwLCJleHAiOjE0OTMxNjU1MDQsImRhdGEiOnsidXNlcklkIjowLCJ1c2VyTmFtZSI6ImZhYmlvIn19.kg6rdKjw8SNkwQkxZq5h1JBx3wDJTHKkvaMW_U4-3RXGb1F3xFN8aNyMDIHnUhSRMecDbqez3J80_jmPNqtH6w", 0]:  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'UPDATE public.usuario SET token = ? WHERE id = ?' with params [\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ5MDAsImp0aSI6IjRQS1RPb2FVRVlWZ3ZVYkFoa0JIUmE5WDVzb2g0ajJ1XC9NNnFYN3c3ME44PSIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIiwibmJmIjoxNDkzMTY0OTAwLCJleHAiOjE0OTMxNjU1MDQsImRhdGEiOnsidXNlcklkIjowLCJ1c2VyTmFtZSI6ImZhYmlvIn19.kg6rdKjw8SNkwQkxZq5h1JBx3wDJTHKkvaMW_U4-3RXGb1F3xFN8aNyMDIHnUhSRMecDbqez3J80_jmPNqtH6w\", 0]:\n\nSQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-25 21:01:40] application.ERROR: An exception occurred while executing 'UPDATE public.usuario SET token = ? WHERE id = ?' with params ["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE0OTMxNjQ5MDAsImp0aSI6IjRQS1RPb2FVRVlWZ3ZVYkFoa0JIUmE5WDVzb2g0ajJ1XC9NNnFYN3c3ME44PSIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIiwibmJmIjoxNDkzMTY0OTAwLCJleHAiOjE0OTMxNjU1MDQsImRhdGEiOnsidXNlcklkIjowLCJ1c2VyTmFtZSI6ImZhYmlvIn19.kg6rdKjw8SNkwQkxZq5h1JBx3wDJTHKkvaMW_U4-3RXGb1F3xFN8aNyMDIHnUhSRMecDbqez3J80_jmPNqtH6w", 0]:  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) [] []
[2017-04-25 21:01:40] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE public.u...', Array) #2 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(669): Doctrine\DBAL\Connection->executeUpdate('UPDATE public.u...', Array, Array) #3 /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php(53): Doctrine\DBAL\Connection->update('public.usuario', Array, Array) #4 [internal function]: MyApp\Controller\AuthenticateController->authenticate(Object(Silex\Application), Object(Symfony\Component\HttpFoundation\Request)) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
