[2017-04-26 23:52:41] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/CarController.php line 53 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/CarController.php:53)"} []
[2017-04-26 23:53:15] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/CarController.php line 53 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/CarController.php:53)"} []
[2017-04-26 23:53:45] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/CarController.php line 53 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/CarController.php:53)"} []
[2017-04-26 23:55:06] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO public.car (nome, ano, aro) VALUES (?, ?, ?)' with params ["Corsa10", "1992", "15"]:  SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "parent_id" violates not-null constraint DETAIL:  Failing row contains (null, Corsa10, 1992, 15). (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 57 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO public.car (nome, ano, aro) VALUES (?, ?, ?)' with params [\"Corsa10\", \"1992\", \"15\"]:\n\nSQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"parent_id\" violates not-null constraint\nDETAIL:  Failing row contains (null, Corsa10, 1992, 15). at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:57, Doctrine\\DBAL\\Driver\\PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"parent_id\" violates not-null constraint\nDETAIL:  Failing row contains (null, Corsa10, 1992, 15). at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"parent_id\" violates not-null constraint\nDETAIL:  Failing row contains (null, Corsa10, 1992, 15). at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-26 23:55:06] application.ERROR: An exception occurred while executing 'INSERT INTO public.car (nome, ano, aro) VALUES (?, ?, ?)' with params ["Corsa10", "1992", "15"]:  SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "parent_id" violates not-null constraint DETAIL:  Failing row contains (null, Corsa10, 1992, 15). [] []
[2017-04-26 23:55:06] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pub...', Array) #2 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pub...', Array, Array) #3 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(56): Doctrine\DBAL\Connection->insert('public.car', Array) #4 [internal function]: MyApp\Controller\CarController->insert(Object(Silex\Application), Object(Symfony\Component\HttpFoundation\Request)) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
