[2017-04-25 23:17:42] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 23:17:42] application.ERROR: No route found for "GET /" [] []
[2017-04-25 23:17:42] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-25 23:17:57] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /admin" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/admin\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 23:17:57] application.ERROR: No route found for "GET /admin" [] []
[2017-04-25 23:17:57] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-25 23:21:03] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:03] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:04] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:04] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:05] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:06] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:07] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:07] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:08] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:08] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:08] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:09] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:09] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:14] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:15] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
[2017-04-25 23:21:16] application.ERROR: Uncaught Exception Error: "Call to a member function get() on null" at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php line 17 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php:17)"} []
