[2017-04-25 00:36:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 00:36:02] application.ERROR: No route found for "GET /" [] []
[2017-04-25 00:36:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 00:36:02] application.DEBUG: < 404 [] []
[2017-04-25 00:56:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 00:56:41] application.ERROR: No route found for "GET /" [] []
[2017-04-25 00:56:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 00:56:41] application.DEBUG: < 404 [] []
[2017-04-25 00:56:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /%C5%82ogin" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /%C5%82ogin\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/%C5%82ogin\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 00:56:45] application.ERROR: No route found for "GET /%C5%82ogin" [] []
[2017-04-25 00:56:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 00:56:45] application.DEBUG: < 404 [] []
[2017-04-25 00:56:48] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /login" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/login\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 00:56:48] application.ERROR: No route found for "GET /login" [] []
[2017-04-25 00:56:48] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 00:56:48] application.DEBUG: < 404 [] []
[2017-04-25 00:57:13] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /login" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/login\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 00:57:13] application.ERROR: No route found for "GET /login" [] []
[2017-04-25 00:57:13] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 00:57:13] application.DEBUG: < 404 [] []
[2017-04-25 00:59:26] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 00:59:26] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 00:59:26] application.DEBUG: < 403 [] []
[2017-04-25 00:59:36] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 00:59:36] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 00:59:36] application.DEBUG: < 403 [] []
[2017-04-25 01:00:24] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:00:24] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:00:24] application.DEBUG: < 403 [] []
[2017-04-25 01:01:02] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:01:02] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:01:02] application.DEBUG: < 403 [] []
[2017-04-25 01:01:45] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:01:45] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:01:45] application.DEBUG: < 403 [] []
[2017-04-25 01:02:07] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:02:07] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:02:07] application.DEBUG: < 403 [] []
[2017-04-25 01:02:21] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:02:21] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:02:21] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] invalid port number: "null" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] invalid port number: \"null\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] invalid port number: \"null\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] invalid port number: \"null\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-04-25 01:02:21] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] invalid port number: "null" [] []
[2017-04-25 01:02:21] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', '32736384', Array) #3 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array, Array) #5 /var/www/html/n2oti/src/MyApp/Controller/AuthenticateController.php(19): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM p...', Array) #6 [internal function]: MyApp\Controller\AuthenticateController->authenticate(Object(Silex\Application), Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #12 {main} [] []
[2017-04-25 01:02:21] application.DEBUG: < 500 [] []
[2017-04-25 01:02:51] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:02:51] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:02:51] application.DEBUG: < 200 [] []
[2017-04-25 01:02:52] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:02:52] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:02:52] application.DEBUG: < 200 [] []
[2017-04-25 01:03:35] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:03:35] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:03:40] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:03:40] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:04:29] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:04:29] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:04:40] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:04:40] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:04:40] application.DEBUG: < 200 [] []
[2017-04-25 01:05:16] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:05:16] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:05:16] application.DEBUG: < 403 [] []
[2017-04-25 01:05:17] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:05:17] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:05:17] application.DEBUG: < 403 [] []
[2017-04-25 01:05:44] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:05:44] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:05:44] application.DEBUG: < 200 [] []
[2017-04-25 01:05:45] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:05:45] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:05:45] application.DEBUG: < 200 [] []
[2017-04-25 01:05:46] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login?pass=123&user=fabio","method":"GET"} []
[2017-04-25 01:05:46] application.DEBUG: > GET /app_dev.php/api/v1/login?user=fabio&pass=123 [] []
[2017-04-25 01:05:46] application.DEBUG: < 200 [] []
[2017-04-25 01:05:52] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/book" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/book\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/book\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 01:05:52] application.ERROR: No route found for "GET /api/v1/book" [] []
[2017-04-25 01:05:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 01:05:52] application.DEBUG: < 404 [] []
[2017-04-25 01:08:02] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:08:02] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:08:02] application.DEBUG: < 403 [] []
[2017-04-25 01:08:11] application.INFO: Matched route "{route}". {"route":"_api_v1_login","route_parameters":{"_controller":"\\MyApp\\Controller\\AuthenticateController::authenticate","_route":"_api_v1_login"},"request_uri":"http://localhost:8000/app_dev.php/api/v1/login","method":"GET"} []
[2017-04-25 01:08:11] application.DEBUG: > GET /app_dev.php/api/v1/login [] []
[2017-04-25 01:08:11] application.DEBUG: < 403 [] []
[2017-04-25 01:08:50] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/book" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/book\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/book\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-25 01:08:50] application.ERROR: No route found for "GET /api/v1/book" [] []
[2017-04-25 01:08:50] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/app_dev.php(25): Silex\Application->run() #8 {main} [] []
[2017-04-25 01:08:50] application.DEBUG: < 404 [] []
